receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  # Send metrics to Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Also log to console for debugging
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
      
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]